import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("BINANCE_KEY")
API_SECRET = os.getenv("BINANCE_SECRET")

SYMBOL = 'BTC/USDT'
TIMEFRAME = '5m'
LIMIT = 200
AMOUNT = 0.001

STOP_LOSS_PCT = 0.01
TAKE_PROFIT_PCT = 0.02

BASE_ATR_MULT = 1.5
MIN_ATR_MULT = 1.2
MAX_ATR_MULT = 4.0
ATR_PERIOD = 14
ATR_MEAN_PERIOD = 50
TRAIN_INTERVAL = 30
TRAIN_MONTHS = 6

DCA_MAX_BUYS = 3
DCA_DROP_PCT = 0.03

MIN_NOTIONAL = 5
